import { defineConfig, s } from "velite";
export default defineConfig({
  collections: {
    articles: {
      name: "Article",
      pattern: "articles/**/*.md",
      schema: s.object({
        id: s.string(),
        slug: s.slug("articles"),
        title: s.string().max(99),
        date: s.isodate(),
        last_update: s.isodate(),
        authorId: s.string(),
        categoryId: s.string(),
        issueId: s.string().optional(),
        in_evidence: s.boolean().default(false),
        published: s.boolean().default(false),
        content: s.markdown(),
        excerpt: s.string().max(200),
        podcastId: s.string().optional(),
        createdBy: s.string(),
      }),
    },
    podcasts: {
      name: "Podcast",
      pattern: "podcasts/**/*.json",
      schema: s.object({
        id: s.string(),
        slug: s.slug("podcasts"),
        title: s.string().max(99),
        description: s.string(),
        date: s.isodate(),
        last_update: s.isodate(),
        audio: s.string(),
        audio_chunks: s.string(),
        issueId: s.string().optional(),
        published: s.boolean().default(false),
        createdBy: s.string(),
      }),
    },
    authors: {
      name: "Author",
      pattern: "authors/**/*.json",
      schema: s.object({
        id: s.string(),
        slug: s.slug("authors"),
        name: s.string(),
        description: s.string(),
        createdBy: s.string(),
      }),
    },
    categories: {
      name: "Category",
      pattern: "categories/**/*.json",
      schema: s.object({
        id: s.string(),
        slug: s.slug("categories"),
        name: s.string(),
        description: s.string(),
        createdBy: s.string(),
      }),
    },
    issues: {
      name: "Issue",
      pattern: "issues/**/*.json",
      schema: s.object({
        id: s.string(),
        slug: s.slug("issues"),
        date: s.isodate(),
        last_update: s.isodate(),
        title: s.string(),
        description: s.string(),
        cover: s.string(),
        color: s.string(),
        published: s.boolean().default(false),
        articlesOrder: s.array(s.string()).default([]),
        showOrder: s.boolean().default(false),
        createdBy: s.string(),
      }),
    },
    pages: {
      name: "Page",
      pattern: "pages/**/*.md",
      schema: s.object({
        id: s.string(),
        slug: s.slug("pages"),
        title: s.string().max(99),
        excerpt: s.string().max(200),
        content: s.markdown(),
        createdBy: s.string(),
      }),
    },
  },
});
