// This file is generated by Velite

export { default as articles } from './articles.json' with { type: 'json' }
export { default as podcasts } from './podcasts.json' with { type: 'json' }
export { default as authors } from './authors.json' with { type: 'json' }
export { default as categories } from './categories.json' with { type: 'json' }
export { default as issues } from './issues.json' with { type: 'json' }
export { default as pages } from './pages.json' with { type: 'json' }