// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Article = Collections['articles']['schema']['_output']
export declare const articles: Article[]

export type Podcast = Collections['podcasts']['schema']['_output']
export declare const podcasts: Podcast[]

export type Author = Collections['authors']['schema']['_output']
export declare const authors: Author[]

export type Category = Collections['categories']['schema']['_output']
export declare const categories: Category[]

export type Issue = Collections['issues']['schema']['_output']
export declare const issues: Issue[]

export type Page = Collections['pages']['schema']['_output']
export declare const pages: Page[]
